server:
  port: 8006
spring:
  application:
    name: cloud-providerConsul-payment-8006
  cloud:
    consul:
      host: 192.168.8.128
      port: 8500
      discovery:
        service-name: ${spring.application.name}